# Configuración del OTEL Collector (Gateway)
extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        
  awsecscontainermetrics:
    collection_interval: 10s

processors:
  batch:

exporters:
  datadog:
    api:
      key: ${DD_API_KEY} 
      site: us5.datadoghq.com
  debug:
    verbosity: detailed

service:
  extensions: [health_check] 
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      # AQUÍ ESTÁ EL CAMBIO: Agregamos datadog
      exporters: [datadog, debug] 
    metrics:
      receivers: [otlp, awsecscontainermetrics] 
      processors: [batch]
      # AQUÍ ESTÁ EL CAMBIO
      exporters: [datadog, debug] 
    logs:
      receivers: [otlp]
      processors: [batch]
      # AQUÍ ESTÁ EL CAMBIO
      exporters: [datadog, debug]